version: '3'
services:
  mqtt-explorer:
    build: 
      context: .
      target: builder
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - HOSTNAME=0.0.0.0
      - PORT=3000
      - MQTT_URL=mqtt://localhost:1883
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev 